apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: ingress-basic
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rik.merkens@student.hu.nl
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
